import dotenv from "dotenv"
dotenv.config()

const {DB, HOST, PORT_API, ACCESS_TOKEN, REFRESH_TOKEN, MERCADO_PAGO_KEY, CLIENT_URL, API_NOTIFICATION_URL} = process.env;

export default  {
    MONGO_DATABASE: DB, // DB
    MONGO_USER: "admin",
    MONGO_PASSWORD: "admin",
    MONGO_HOST: HOST,
    PORT: PORT_API || 3002,
    ACCESS_TOKEN: ACCESS_TOKEN,
    REFRESH_TOKEN: REFRESH_TOKEN,
    MERCADO_PAGO_ACCESS: MERCADO_PAGO_KEY,
    CLIENT_URL: CLIENT_URL,
    API_NOTIFICATION_URL: API_NOTIFICATION_URL
}
