export const componentsArray = [
    {
        //: 1,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683234206/ecommerce/trdzfr02bpu0rxdqkfaw.webp",
        title: "MOTHER ASUS (AM5) ROG STRIX B650E-E GAMING WFI",
        brand: "Asus",
        description: [
          "AMD Socket AM5 for AMD Ryzen 7000 Series Desktop Processors",
          "Total supports 4 x M.2 slots and 4 x SATA 6Gb/s ports",
          "ROG SupremeFX 7.1 Surround Sound High Definition Audio CODEC ALC4080",
          "4x DIMM Slots, DDR5 6400MHz, PCIe Gen 5, 4x SATA 6Gb/s connectors, 4xM.2 Slot, 2.5GB LAN",
          "Graphics: 1 x DisplayPort* 1 x HDMI® port",
          "Expansion Slots AMD Ryzen™ 7000 Series Desktop Processors*",
        ],
        price: 217.453,
        category: "Motherboard",
        stock: 0,
        banned: false,
      },
      {
        //: 4,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683230434/ecommerce/nkpx1dmchavchbvi5nss.jpg",
        title: "ASRock H310CM-HDV LGA1151/Intel H310/DDR4/SATA3&USB3.1",
        brand: "ASRock",
        description: [
          "Intel LGA 1151 socket",
          "DDR4 memory compatibility",
          "M.2 for SSDs",
          "Realtek Gigabit LAN",
          "5X Protection II for hardware-level safeguards",
        ],
        price: 68.99,
        category: "Motherboard",
        stock: 8,
        banned: false,
      },
      {
        //: 5,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683230448/ecommerce/gc8ube8gmdijzjbqp4vj.jpg",
        title: "MSI MPG Z590 Gaming Edge WiFi ATX Gaming Motherboard",
        brand: "MSI",
        description: [
          "Supports 11th and 10th Gen Intel Core/Pentium/Celeron processors",
          "DDR4 Memory, up to 5333 MHz",
          "Lightning-fast experience: PCIe 4.0, Lightning Gen 4 M.2",
          "Wi-Fi 6E ready: 6GHz band prov//es the next level of Wi-Fi",
        ],
        price: 68.99,
        category: "Motherboard",
        stock: 10,
        banned: false,
      },
      {
        //: 3,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683234423/ecommerce/18921-2_dnu6lx.jpg",
        title: "AURICULAR GAMER REDRAGON LAMIA H320",
        brand: "Redragon",
        description: [
          "Longitud: 180 mm",
          "Ancho: 105 mm",
          "Profund//ad: 200 mm",
          "Peso: 290 g",
          "Microfono : Omn//ireccional con cancelacion de ru//o, con boton de muteo.Compatibil//ad : PC, Xbox, PlayStation, Nintendo Switch y dispositivos móviles con toma de audio de 3,5 mm",
          "Respuesta de frecuencia: 20 Hz - 20 KHz",
        ],
        price: 49.99,
        category: "Auriculares",
        stock: 5,
        banned: false,
      },
      {
        //: 4,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683234433/ecommerce/D_NQ_NP_713953-MLA29337198688_022019-O_pvy60e.jpg",
        title: "LOGITECH G633 ARTEMIS SPECTRUM",
        brand: "Logitech",
        description: [
          "Longitud: 182 mm",
          "Ancho: 81.7 mm",
          "Profund//ad: 182 mm",
          "Peso: 374 g",
          "Microfono: Micrófono con brazo ajustable y cancelación de ru//o",
          "Respuesta de frecuencia: 20 Hz - 20 KHz",
        ],
        price: 149.99,
        category: "Auriculares",
        stock: 8,
        banned: false,
      },
      {
        //: 3,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683235304/ecommerce/micro-intel-core-i9-11900k-8core-16m-35ghz-1200-1_noucgd.jpg",
        title: "Intel Core i9-11900K",
        brand: "Intel",
        description: [
          "Núcleos: 8",
          "Hilos: 16",
          "Veloc//ad base: 3.5 GHz",
          "Veloc//ad turbo: 5.3 GHz",
          "Cache: 16MB",
          "Socket: LGA1200",
          "Consumo energético: 125W",
          "Tecnología de fabricación: 14nm",
        ],
        price: 549.99,
        category: "Procesadores",
        stock: 8,
        banned: false,
      },
  
      {
        //: 4,
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683235323/ecommerce/Ryzen-9-Ventila_CC_81tor-ne_CC_81lku_CC_88li-1_gllqjj.jpg",
        title: "AMD Ryzen 9 5950X",
        brand: "AMD",
        description: [
          "Núcleos: 16",
          "Hilos: 32",
          "Veloc//ad base: 3.4 GHz",
          "Veloc//ad turbo: 4.9 GHz",
          "Cache: 72MB",
          "Socket: AM4",
          "Consumo energético: 105W",
          "Tecnología de fabricación: 7nm",
        ],
        price: 999.99,
        category: "Procesadores",
        stock: 5,
        banned: false,
      },
      {
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683238587/ecommerce/71FeUtw_TPL._SL1500__okn9ch.jpg",
        title: "Notebook HP Pavilion Gaming 15-EC1023AX",
        brand: "HP",
        description: [
          "Procesador: AMD Ryzen 5 5600H",
          "Tarjeta de video: NVIDIA GeForce GTX 1650 4GB GDDR6",
          "Frecuencia: 4.2 GHz",
          "Memoria ram: 8GB DDR4 3200MHz",
          "Almacenamiento: 512GB SSD PCIe NVMe M.2",
          "Resolución: 1920x1080 144Hz",
          "Tamaño: 15.6",
        ],
        price: 799.99,
        category: "Notebooks",
        stock: 7,
        banned: false,
      },
      {
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683238603/ecommerce/MSI_2BGL75_2BLeopard_2B10SEK-040XES_dhnwla.jpg",
        title: "MSI GL65 9SD-266XES",
        brand: "MSI",
        description: [
          "Procesador: Intel Core i7-9750H",
          "Tarjeta de video: NVIDIA GeForce GTX 1660 Ti 6GB",
          "Frecuencia: 2.6 GHz (hasta 4.5 GHz)",
          "Memoria ram: 16GB DDR4 (2666 MHz)",
          "Almacenamiento: SSD 512GB",
          "Resolución: Full HD 1920x1080 (120 Hz)",
          "Tamaño: 15.6",
        ],
        price: 1299.0,
        category: "Notebooks",
        stock: 8,
        banned: false,
      },
      {
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683241259/ecommerce/719dUNo9gDS._AC_SX522__fpe0wj.jpg",
        title: "ASUS TUF Gaming NVIDIA GeForce RTX 3060",
        brand: "Nvidia",
        description: [
          "Memoria: 12 GB, 192 bit GDDR6, 15000 MHz ",
          "Interfaz: PCIe 4.0 16x, HDMI, DisplayPort",
          "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
          "Max Digital : 7680x4320",
          "Boost Clock: 1777 MHz",
        ],
        price: 2799.99,
        category: "Placas de video",
        stock: 5,
        banned: false,
      },
      {
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683241280/ecommerce/concepto-6449140_tszmpl.jpg",
        title: "Gigabyte Radeon RX 6600 XT GAMING OC 8GB",
        brand: "AMD",
        description: [
          "Memoria: 8 GB, 128 bit GDDR6, 16000 MHz",
          "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4a",
          "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
          "Max Digital : 7680x4320",
          "Boost Clock: 2589 MHz",
        ],
        price: 2399.99,
        category: "Placas de video",
        stock: 2,
        banned: false,
      },
      {
        image:
          "https://res.cloudinary.com/dezvujzed/image/upload/v1683241298/ecommerce/51PoGBuf0nL._AC__kkhclb.jpg",
        title: "Sapphire Radeon RX 6900 XT Nitro+",
        brand: "AMD",
        description: [
          "Memoria: 16 GB, 256 bit GDDR6, 16000 MHz",
          "Interfaz: PCIe 4.0 16x, HDMI 2.1, DisplayPort 1.4",
          "Soporte de Sistema Operativo: Windows 10 64bit, Linux 64bit",
          "Max Digital: 7680x4320",
          "Boost Clock: 2365 MHz",
        ],
        price: 3999.99,
        category: "Placas de video",
        stock: 1,
        banned: false,
      },
]